version: "3.7"

services:
  # Postgres db
  diagnosis.db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME:?err}
      POSTGRES_USER: ${POSTGRES_USER:?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
    container_name: diagnosis-db

  # Application
  diagnosis.api:
    build:
      context: .
      dockerfile: Dockerfile
    image: diagnosis.api:latest
    command: ./scripts/run-server.sh --docker --prod
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - diagnosis.db
    container_name: diagnosis-api

volumes:
  pg_data:
