# Generated by Django 4.2.2 on 2023-06-08 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("category_code", models.CharField(max_length=25, unique=True)),
                ("category_title", models.CharField(max_length=1024)),
            ],
            options={
                "ordering": ["category_code"],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "icd_type",
                    models.CharField(
                        choices=[
                            ("ICD_9", "ICD_9"),
                            ("ICD_10", "ICD_10"),
                            ("ICD_11", "ICD_11"),
                        ],
                        default="ICD_10",
                        max_length=12,
                    ),
                ),
                ("diagnosis_code", models.CharField(blank=True, max_length=10)),
                ("abbreviated_desc", models.CharField(max_length=2048)),
                ("full_desc", models.TextField(max_length=2048)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="icd.category"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
