# Generated by Django 4.2.2 on 2023-06-13 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import icd.extensions


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("category_code", models.CharField(max_length=25, unique=True)),
                ("category_title", models.CharField(max_length=1024)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["category_code"],
            },
        ),
        migrations.CreateModel(
            name="ICDFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=icd.extensions.file_upload_path)),
                (
                    "record_type",
                    models.CharField(
                        choices=[("Category", "Category"), ("Diagnosis", "Diagnosis")],
                        max_length=12,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "icd_type",
                    models.CharField(
                        choices=[
                            ("ICD_9", "ICD_9"),
                            ("ICD_10", "ICD_10"),
                            ("ICD_11", "ICD_11"),
                        ],
                        default="ICD_10",
                        max_length=12,
                    ),
                ),
                ("diagnosis_code", models.CharField(blank=True, max_length=10)),
                (
                    "abbreviated_desc",
                    models.CharField(
                        max_length=2048, verbose_name="abbreviated description"
                    ),
                ),
                (
                    "full_desc",
                    models.TextField(max_length=2048, verbose_name="full description"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="icd.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Diagnoses",
                "ordering": ["id"],
            },
        ),
    ]
