# Generated by Django 4.2.2 on 2023-06-09 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("icd", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Files",
            new_name="File",
        ),
        migrations.AlterModelOptions(
            name="diagnosis",
            options={"verbose_name_plural": "Diagnoses"},
        ),
    ]
