# Generated by Django 4.2.2 on 2023-06-12 13:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("icd", "0002_alter_diagnosis_category_alter_file_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="File",
            new_name="CSVFile",
        ),
    ]
