# Generated by Django 4.2.2 on 2023-06-10 22:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("icd", "0003_alter_diagnosis_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["category_code"], "verbose_name_plural": "Categories"},
        ),
    ]
