# Generated by Django 4.2.2 on 2023-06-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icd", "0003_rename_file_csvfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="abbreviated_desc",
            field=models.CharField(
                max_length=2048, verbose_name="abbreviated description"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="full_desc",
            field=models.TextField(max_length=2048, verbose_name="full description"),
        ),
    ]
