# Generated by Django 4.2.2 on 2023-06-12 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("icd", "0004_alter_diagnosis_abbreviated_desc_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="csvfile",
            old_name="type",
            new_name="data_type",
        ),
    ]
