# Generated by Django 4.2.2 on 2023-06-12 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("icd", "0005_rename_type_csvfile_data_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="csvfile",
            old_name="data_type",
            new_name="file_type",
        ),
    ]
